/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PredictionMarket__factory } from "./PredictionMarket__factory";
export { WTRUST__factory } from "./WTRUST__factory";
